### ISSUE TITLE
Not reading azure.activedirectory properties from Spring Property file passed by -Dspring.config.location=<property file>

### ISSUE THREAD

**Issue by prabdeb** [microsoft/azure-spring-boot#926] opened 2020-06-22 08:52 UTC
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Linux
- Java version: 
  - 1.8

## Summary
No reading `azure.activedirectory` properties (Ex. `azure.activedirectory.tenant-id`) from Spring Property file passed by `-Dspring.config.location=<property file>` in Java Command line while starting the application

## Reproduce steps
Do not hard code `azure.activedirectory.*` properties in a file `application.properties` instead have them in a property file, created in a location other than `classpath` and passed to JVM using Spring Option - `-Dspring.config.location=<property file>`

## Expected Results
Should read the properties from a file that is not in `classpath` and loaded via Spring Option

## Actual Results
Receiving exception - `azure.activedirectory.tenant-id not found`

## Workaround
Instead of passing `-Dspring.config.location=<property file>` in Java Command Line while starting application, rename the `<property file>` into `application.properties` and place into the same directory from where the Java Command Line is triggered to start the application - Ex.

`cp $PROPERTY_FILE_PATH /home/user/application.properties && cd /home/user
          && java -jar application.war`

**Comment by saragluna** [comment] 2020-06-22 12:52
Thanks for reaching out. Is the issue #927 related to this one?

**Comment by prabdeb** [comment] 2020-06-22 13:06
@saragluna No this two issues are separate. Thanks for considering this issue!

**Comment by chenrujun** [comment] 2020-06-28 09:36
Hi, @prabdeb .

I can not reproduce you problem in my localhost with our [sample app](https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample/src/main/java/sample/aad/AzureADOAuth2BackendSampleApplication.java).


Here is the screenshot: 
![2020-06-28](https://user-images.githubusercontent.com/13167207/85943913-c66ba400-b965-11ea-806d-1dab0089c225.PNG)


1. Which version are you using?
2. Could you please try to use the [sample app](https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample/src/main/java/sample/aad/AzureADOAuth2BackendSampleApplication.java) to reproduce your problem?

**Comment by prabdeb** [comment] 2020-07-01 07:55
Yes @chenrujun the application is starting without any error, but while trying to access the api I am getting 403 forbidden error, where the bearer token is correct only.

However if I do this `cp $PROPERTY_FILE_PATH /home/user/application.properties && cd /home/user && java -jar application.war` then the authentication is working properly

cc: @salujamanish

**Comment by chenrujun** [comment] 2020-07-02 01:45
@prabdeb .

> if the property file does not have extension .properties this will not work

Yes, that is the root cause. It has already been discussed in [stackoverflow](https://stackoverflow.com/questions/43744892/spring-config-location-is-ignored). 

And I find [related code in spring boot](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/PropertiesPropertySourceLoader.java#L42).

> And for our use case since we are reading from Azure Key Vault, there we can not store any secret file with . in name

Could you please save `abc` in Key Vault, and rename to `abc.properties` when use it?

i.e.
change
```
cp $PROPERTY_FILE_PATH /home/user/application.properties && cd /home/user && java -jar application.war
```
to 
```
mv $PROPERTY_FILE_PATH ${PROPERTY_FILE_PATH}.properties && java -Dspring.config.location=${PROPERTY_FILE_PATH}.properties -jar /home/user/application.war
```

**Comment by chenrujun** [comment] 2020-07-06 02:09
I'll close this issues because it's caused by spring framework restriction, not by our starter module.

**Closed by chenrujun** 2020-07-06 02:09 UTC
Labels: aad

**Comment by scgbear** [comment] 2020-07-08 16:56
<details>
<summary>Internal Tracking</summary>
CSEF368746
</details>

**Comment by philwebb** [comment] 2020-08-25 21:01
To help with this, as of Spring Boot 2.4.0-M3 you can import extensionless files by using an extension hint. See https://github.com/spring-projects/spring-boot/issues/22280 for details.

**Comment by chenrujun** [comment] 2020-08-26 02:08
@philwebb Thank you for your information.
