### ISSUE TITLE
Intermittent timeout connecting to azure service bus

### ISSUE THREAD

**Issue by hrtummala** [Microsoft/azure-spring-boot#343] opened 2018-05-30 16:10 UTC
## Environment
- Spring boot starter:
  
 
  - service bus spring boot starter

  
- OS Type: Linux
- Java version: 
  
  - 1.8

  

## Summary
We are experiencing Timeout issues with Azure service bus intermittently when SENDING messages. This is happening  running with out issues for number of days. The load when this is happening is minimal to none as this is in DEV. 

We are using standard queue in azure. The client app is not able to reconnect again and throwing the below error: 
2018-05-30T09:12:38.532-04:00 [APP/PROC/WEB/0] [OUT] 2018-05-30 13:12:38.532 ERROR 17 --- [onPool-worker-0] c.m.a.s.primitives.MessagingFactory : Sending CBS Token for amqp://abcd.servicebus.windows.net/abcd failed.
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] java.util.concurrent.CompletionException: com.microsoft.azure.servicebus.primitives.TimeoutException: Request timed out.
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at com.microsoft.azure.servicebus.primitives.RequestResponseLink.exceptionallyCompleteRequest(RequestResponseLink.java:269) ~[azure-servicebus-1.0.0.jar!/:na]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at com.microsoft.azure.servicebus.primitives.RequestResponseLink.access$1000(RequestResponseLink.java:43) ~[azure-servicebus-1.0.0.jar!/:na]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at com.microsoft.azure.servicebus.primitives.RequestResponseLink$3.run(RequestResponseLink.java:250) ~[azure-servicebus-1.0.0.jar!/:na]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] Caused by: com.microsoft.azure.servicebus.primitives.TimeoutException: Request timed out.
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] ... 8 common frames omitted
2018-05-30T09:12:38.533-04:00 [APP/PROC/WEB/0] [OUT] 2018-05-30 13:12:38.532 INFO 17 --- [onPool-worker-0] c.m.a.s.primitives.MessagingFactory : Will retry sending CBS Token for amqp://mmsjdeardev.servicebus.windows.net/arjdepaymentsdev after 5 seconds.

We have to restart the client app in order again to get the connections back. 
## Reproduce steps
Can not do on demand. Happening intermittent. 

## Expected Results
 The request can fail throwing communication exception but should able to restore communication later with Azure service bus.
[service bus error.txt](https://github.com/Microsoft/azure-spring-boot/files/2054739/service.bus.error.txt)

 

## Actual Results
The request is timing out and the connection is not getting restored until the application is restarted.

**Comment by hrtummala** [comment] 2018-09-25 15:29
@sophiaso I just want to check if this issue is fixed in Azure Service bus API 1.2.8 release? I see comment from @yvgopal :Made some changes to stop using ForkJoinPool.commonPool and instead creates its own executor service. Clients are also encourage to pass their own executor service when registering IMessageHandler or ISessionHandler.
These changes are aimed at fixing timeouts caused by thread starvation issues like #273.

**Comment by yvgopal** [comment] 2018-09-27 20:03
I don't know yet know what caused your timeouts. The bug I fixed in 1.2.8 fixes timeouts caused by a specific issue. You can try and see if your issue is also resolved.

**Comment by hrtummala** [comment] 2018-09-27 20:10
> I don't know yet know what caused your timeouts. The bug I fixed in 1.2.8 fixes timeouts caused by a specific issue. You can try and see if your issue is also resolved.

Thanks @yvgopal we just deployed in DEV and will observe if that fixes the intermittent timeouts. The timeout on our end is happening when we the application for example is not in use for several hours and then starts throwing the above error on this issue.

**Comment by xscript** [comment] 2018-11-21 02:36
@hrtummala Is your issue resolved?

**Comment by xscript** [comment] 2018-11-21 14:50
Great to know. Then I will close this issue.  :)

**Closed by xscript** 2018-11-21 14:50 UTC
Labels: service bus
