### ISSUE TITLE
azure spring boot starters not available in Spring Initializr 

### ISSUE THREAD

**Issue by rajadilipkolli** [Microsoft/azure-spring-boot#21] opened 2017-07-03 10:13 UTC
azure spring boot starters not available in Spring Initializr as mentioned in readme.md file

**Comment by ZhijunZhao** [comment] 2017-07-04 01:55
We're working on it to make it happen.

**Comment by snicoll** [comment] 2017-09-06 18:24
Duplicate of https://github.com/spring-io/initializr/pull/492

**Closed** 2017-10-25 02:53 UTC
Labels: integration
