### ISSUE TITLE
Branch out 2.0.x and release

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/azure-spring-boot#466] opened 2018-11-19 01:51 UTC
- [x] Create new branch 2.0.x for Spring Boot version 2.0.x, use Spring Boot version 2.0.6.RELEASE
- [x] Release version for branch 2.0.x
- [x] Update master Spring Boot version to 2.1.0.RELEASE, #485 
- [x] Release version 2.1.0 for Spring Boot 2.1.0.RELEASE
- [x] Update [Branch and release wiki](https://github.com/Microsoft/azure-spring-boot/wiki/Branch-and-release)

## Master version 2.0.8-SNAPSHOT
- [x] Release version `2.0.8`. PR #498.

**Comment by Incarnation-p-lee** [comment] 2018-12-04 06:15
Update last step to `branch and release wiki.`

**Comment by elhoo** [comment] 2018-12-04 09:14
Any estimate when 2.0.8 will be released? It is now 3 weeks ago #456 was merge which we are waiting for.

**Comment by xscript** [comment] 2018-12-06 02:18
@elhoo We plan to release 2.0.8 before the end of next week. We will update you about any progress.

**Comment by zwolsman** [comment] 2018-12-18 14:40
Any updates when the support for 2.1.x will be available? 2.1.0 has ben out for more than a month now.

**Comment by Incarnation-p-lee** [comment] 2018-12-19 00:54
It is still under work, as some dependencies like cosmosdb and gremlin starters also need to upgrade to 2.1.x, hope everything about 2.1.x will be available before the end of this week.

**Comment by zwolsman** [comment] 2018-12-26 16:30
@Incarnation-p-lee It works if you don't configure the http security.


```kotlin
 override fun configure(http: HttpSecurity) {
        http
                .authorizeRequests()
                .anyRequest().authenticated()
                .and()
                .oauth2Login()

                .userInfoEndpoint()
                .oidcUserService(oidcUserService)
    }
```

This will still cause the error 

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
```

**Comment by Incarnation-p-lee** [comment] 2018-12-27 00:58
@zwolsman 
Thanks for your feedback, could you please share more details about this issue, like version you leverage of this repo, spring boot version, as well as the sample code you are running ?

**Comment by frjtrifork** [comment] 2019-01-03 21:56
> ```
> java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> ```

I had this error also.
It is caused by a version mismatch between spring boot security and adal4j.
They both depend on the oauth2-oidc-sdk dependency - but spring boot security uses 6.x and adal4j uses 5.64.4. 

I specified the version that adal4j depends on in my build.gradle file and it resolved the classcastexception. 

I don't use anything else that depends on the oauth2-oidc-sdk, so pulling the version down to 5.64.4 have not caused problems for me.

Add something like this to your build.gradle file / pom.xml
compile("com.nimbusds:oauth2-oidc-sdk:5.64.4")

**Comment by Incarnation-p-lee** [comment] 2019-01-04 01:05
@frjtrifork 
Yes, we did not involve the version override for gradle yet, as I am not very familiar with gradle version management. Thanks for you information, as spring security guys words, they do not involve any sdk with breaking changes. So here use 5.64.4 for nimbusds may have minor impacts. We may fix this for gradle later.

**Comment by Incarnation-p-lee** [comment] 2019-01-22 06:34
@frjtrifork 
As we have another issue #530 for version control from gradle, will close this issue right now.

**Closed by Incarnation-p-lee** 2019-01-22 06:34 UTC
