### ISSUE TITLE
Why is azure-keyvault-secrets-spring-boot-starter trying to autoconfigure documentDB

### ISSUE THREAD

**Issue by zhouchong90** [microsoft/azure-spring-boot#606] opened 2019-03-01 04:09 UTC
## Environment
- Spring boot starter:
  
  - key vault spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 1.8
  
## Summary
The azure-keyvault-secrets-spring-boot-starter package tries to autoconfigure my DocumentDB, which violates the whole point of using key vault. 

## Reproduce steps

Create a project that includes the latest version of azure-keyvault-secrets-spring-boot-starter, and also configure a document client bean.

## Expected Results
I can choose my own properties, such as azure-cosmosdb-key, put it in key-vault, and use it with @Value annotation.

## Actual Results
Shows this error message.

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'azure.cosmosdb' to com.microsoft.azure.spring.autoconfigure.cosmosdb.DocumentDBProperties failed:

    Property: azure.cosmosdb.key
    Value: null
    Reason: must not be empty

    Property: azure.cosmosdb.uri
    Value: null
    Reason: must not be empty

    Property: azure.cosmosdb.database
    Value: null
    Reason: must not be empty

Action:

Update your application's configuration

**Comment by sophiaso** [comment] 2019-03-01 05:03
Hi @zhouchong90, thanks for opening issue, if possible, please share a simple sample to reproduce your issue, or share the most essential code to help produce the issue.

If following the below steps:

1. Create `azure-cosmosdb-key` secret in key vault
2. Use the `@Value` to create the document client.
```@SpringBootApplication
public class SampleApplication {
    @Value("${azure.cosmosdb.key}")
    private String cosmosdbKey;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @Bean
    public DocumentClient client() {
        System.out.println("cosmosdb key: " + cosmosdbKey);
        return null; // Omitted the actual creation here
    }
}
```

Before creating the `DocumentClient` bean, the cosmosdb key is already provisioned.

**Comment by jonno85** [comment] 2021-02-22 13:41
Hello,
I'm trying to let the CosmosDbconfiguration loads the Cosmos primary key from the keyvault using a SecretClient (Keyvault) but apparently the property:
    Property: azure.cosmosdb.key
    Value: null

is mandatory.

Is there a proper way to do that, instead of relying on key injection from the Azure CI pipeline?

**Comment by yiliuTo** [comment] 2021-02-25 01:40
Hi @jonno85 , could you share a sample code project or code snippet to help us debug?

**Comment by chenrujun** [comment] 2021-03-09 08:18
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:18 UTC
Labels: azure-spring, key vault
