### ISSUE TITLE
Failed to bind properties under 'azure.servicebus.subscription-receive-mode' to com.microsoft.azure.servicebus.ReceiveMode

### ISSUE THREAD

**Issue by vyasamit** [microsoft/azure-spring-boot#651] opened 2019-04-04 18:23 UTC
## Environment
- Spring boot starter:
  
  - service bus spring boot starter
     <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus-spring-boot-starter</artifactId>
            <version>2.0.5</version>
        </dependency>  

OR

    <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus-spring-boot-starter</artifactId>
            <version>2.1.6</version>
        </dependency>  

- OS Type: Windows
- Java version: 
  
  - 1.8
  

## Summary

In application property file azure.servicebus.subscription-receive-mode property defined with value PEEKLOCK or RECEIVEANDDELETE.

On run of spring boot application, it throws below error.

Failed to bind properties under 'azure.servicebus.subscription-receive-mode' to com.microsoft.azure.servicebus.ReceiveMode:

    Property: azure.servicebus.subscription-receive-mode
    Value: RECEIVEANDDELETE
    Origin: class path resource [application.properties]:14:44
    Reason: 0

Action:

Update your application's configuration
## Reproduce steps

Define properties in Application propertis file.

azure.servicebus.connection-string=
azure.servicebus.topic-name=
azure.servicebus.subscription-name=
azure.servicebus.subscription-receive-mode=RECEIVEANDDELETE

In pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.RELEASE</version>
        <relativePath/> 
    </parent>

  
    <properties>
        <java.version>1.8</java.version>
        <azure.version>2.1.6</azure.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
       
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus-spring-boot-starter</artifactId>
            <version>${azure.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

## Expected Results

Expected app run and connect to topic

## Actual Results

Failed to bind properties under 'azure.servicebus.subscription-receive-mode' to com.microsoft.azure.servicebus.ReceiveMode:

    Property: azure.servicebus.subscription-receive-mode
    Value: RECEIVEANDDELETE
    Origin: class path resource [application.properties]:14:44
    Reason: 0

Action:

Update your application's configuration

**Comment by vyasamit** [comment] 2019-04-04 18:25
if azure.servicebus.subscription-receive-mode= is defined empty app starts but you can get messages from subscription. Seems the com.microsoft.azure.servicebus.ReceiveMode is Enum and it is having trouble to convert PEEKLOCK or RECEIVEANDDELETE to values after reading from a property file.

**Comment by Incarnation-p-lee** [comment] 2019-04-10 00:51
@vyasamit 
Thanks for issue this. It looks I cannot reproduce you issue from my env. From you description, seems the properties cannot be converted to class with binding.

From the debugging, I can see the `RECEIVEANDDELETE ` converted to `com.microsoft.azure.servicebus.ReceiveMode.RECEIVEANDDELETE ` correctly when create SubscriptionClient.

So could you have a try to reproduce you issue from our [sample](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-servicebus-spring-boot-sample) project, I am not sure where is the gap here.

**Comment by vyasamit** [comment] 2019-04-10 02:50
[azure-serrvice-bus-demo.zip](https://github.com/Microsoft/azure-spring-boot/files/3061767/azure-serrvice-bus-demo.zip)

Added the DEMO still show issue project.

Run to spring boot entry application java and you will see the error which I am encountering, below image, is the error message screenshot

![image](https://user-images.githubusercontent.com/16547923/55848050-5202d600-5b11-11e9-99cc-0724ab15cbcc.png)

**Comment by Incarnation-p-lee** [comment] 2019-04-10 03:11
Unfortunately, I cannot get your error from your demo project, for both `PEEKLOCK` and `RECEIVEANDDELETE `

See this ![snapshot](https://github.com/Incarnation-p-lee/test/blob/master/Untitled.png)

**Comment by vyasamit** [comment] 2019-04-10 03:18
I ran your Samples that too gave the same issue 

![image](https://user-images.githubusercontent.com/16547923/55849147-3699ca00-5b15-11e9-801b-d1a4cfb61010.png)

Strange....

**Comment by vyasamit** [comment] 2019-04-10 03:22
The last thing comes to my mind is It can be due to a dependency mess.. Let me clean .m2 repo and rebuild .. will update you.

**Comment by vyasamit** [comment] 2019-04-10 03:27
after .m2 clean, still same .. will dig more

**Comment by Incarnation-p-lee** [comment] 2019-04-10 03:30
Could you please share your mvn dependency:tree to me ?

**Comment by vyasamit** [comment] 2019-04-10 14:52
[demo-dependency.txt](https://github.com/Microsoft/azure-spring-boot/files/3064394/demo-dependency.txt)

attached dependency tree output in txt file

**Comment by moarychan** [comment] 2020-09-01 07:00
Hi @vyasamit , is your problem solved? Will close this question two days later, if you have other questions, please report to [new repo ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring).

**Comment by chenrujun** [comment] 2021-03-09 08:19
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:19 UTC
Labels: azure-spring, service bus
