### ISSUE TITLE
NullPointerException after service restart

### ISSUE THREAD

**Issue by berndgoetz** [microsoft/azure-spring-boot#653] opened 2019-04-07 21:40 UTC
## Environment
- Spring Boot 2.1.4
- Spring boot starter:
  - active directory spring boot starter
- OS Type: Windows / any
- Java version: 11

## Summary
It seems that the Azure Active Directory Spring Boot Starter doesn't trigger a relogon after the application was restarted. The security filter should identify this combination and trigger the relogon to create the correct logon state in the application again.

The sample app at https://github.com/berndgoetz/spring-sec-aad-sample can be used to reproduce the issue.

## Reproduce steps
- start app locally
- login to the app
- restart the app

## Expected Results
The application does a relogon (redirect to AAD to setup the authentication)

## Actual Results
The application throws an NullPointerException

**Comment by Incarnation-p-lee** [comment] 2019-04-08 00:27
Thanks for issue this. Do you mean restart the application and then access the `localhost:8080` will NPE, right ?

It looks I cannot reproduce you issue with you sample code from my side, after restart and the access `localhost:8080`, the process of auth will start as first time.

**Comment by berndgoetz** [comment] 2019-04-14 15:53
> Thanks for issue this. Do you mean restart the application and then access the `localhost:8080` will NPE, right ?

Yes.

> It looks I cannot reproduce you issue with you sample code from my side, after restart and the access `localhost:8080`, the process of auth will start as first time.

Hm, where's the difference? I'm using this version of Java 11:

```
C:\Users\srzgob\workspaces\spring-sec-aad-sample-2>java -version
openjdk version "11-ea" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+18)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+18, mixed mode)
```

What else could be different?

**Comment by moarychan** [comment] 2020-09-01 07:07
Hi @berndgoetz , is your problem solved? if not please try to upgrade to the latest version 2.3.3.

**Comment by chenrujun** [comment] 2021-03-09 08:19
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:19 UTC
Labels: aad, azure-spring
