### ISSUE TITLE
Fail to run Azure Storage Spring Boot Starter Sample on Windows Server 2008R2

### ISSUE THREAD

**Issue by kpapadopoul** [microsoft/azure-spring-boot#605] opened 2019-02-28 14:44 UTC
## Environment
- Spring boot starter:
  
  - storage spring boot starter  
- OS Type:
  - Windows
- Java version: 
  
  - 1.8

## Summary
As part of one of our projects, we would like to have a cloud storage to upload files and share them between our teams. So, we opened an account to Azure and tried an investigation how Azure Storage could cover our requirements. As a first step, we chose to run Azure Storage Spring Boot Starter Sample on our servers. Despite the respective sample application was executed successfully on our development PCs (i.e., Windows 7 Professional) when we tried the same on our Windows servers (i.e., Windows Server 2008R2 were installed as OS) we got an IOException that remote host closed the connection.

## Reproduce steps

1. We packaged sample using Maven following the respective instructions (i.e., https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-storage-spring-boot-sample) on Windows 7 dev PC.
2. We run the sample on dev PC using the following command:
java -jar target/azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar
3. Sample was executed successfully creating a container and uploading the sample file on our Storage account
4. JAR file copied to Windows server and executed using the aforementioned command
5. Execution failed with the following error:
java.io.IOException: An existing connection was forcibly closed by the remote host

## Expected Results

No exception to be observed while a new container to be created and the sample file to be uploaded on our Azure Storage Account.

## Actual Results

Please see below the log of the execution failed:
2019-02-28 09:01:34.160  INFO 25044 --- [           main] sample.storage.StorageSampleApplication  : Starting StorageSampleApplication v0.0.1-SNAPSHOT on DBTPA05P with PID 25044 (C:\Users\uoclo\Documents\azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar started by uoclo in C:\Users\uoclo\Documents)
2019-02-28 09:01:34.169  INFO 25044 --- [           main] sample.storage.StorageSampleApplication  : No active profile set, falling back to default profiles: default
2019-02-28 09:01:57.848  INFO 25044 --- [           main] sample.storage.StorageSampleApplication  : Started StorageSampleApplication in 24.587 seconds (JVM running for 25.794)
Start creating container azure-storage-sample...
2019-02-28 09:04:00.993  INFO 25044 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-02-28 09:04:01.005 ERROR 25044 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at sample.storage.StorageSampleApplication.main(StorageSampleApplication.java:42) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [azure-storage-spring-boot-sample-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.RuntimeException: java.io.IOException: An existing connection was forcibly closed by the remote host
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46) ~[rxjava-2.2.5.jar!/:na]
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93) ~[rxjava-2.2.5.jar!/:na]
        at io.reactivex.Single.blockingGet(Single.java:2807) ~[rxjava-2.2.5.jar!/:na]
        at sample.storage.StorageService.createContainer(StorageService.java:69) ~[classes!/:0.0.1-SNAPSHOT]
        at sample.storage.StorageSampleApplication.run(StorageSampleApplication.java:49) [classes!/:0.0.1-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        ... 13 common frames omitted
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_201]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_201]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]

**Comment by Incarnation-p-lee** [comment] 2019-03-02 14:50
@kpapadopoul 
Thanks for your issue. It looks the same jar works well but got some network issue from windows server 2008R2, right ? If so it seems that due to network issue instead of jar itself. We may need to prepare env to try to reproduce your issue. It may take some time indeed, or you may can provide one env for this if urgent.

**Comment by kpapadopoul** [comment] 2019-03-04 07:56
@Incarnation-p-lee 
We tried remote debugging on Windows Server from our development PCs and we observed that our application performed HTTP access (i.e,, when executing PUT request that used by Azure SDK to create a container) instead of HTTPS (as should be based on Azure Storage configuration) when executed on Windows Servers. On the contrary, the latter didn't happen when our application is executed on development PCs. Trying to step-by-step debugging Azure SDK behavior, we found that there is a configuration property of the respective Spring Boot Starter to enable HTTPS explicitly. After enabling HTTPS, problem was solved. As a proposal, I think the aforementioned property (i.e., azure.storage.enable-https) and its effect should be referred to the README of the azure-storage-spring-boot-starter (i.e., https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-storage-spring-boot-starter/README.md) to avoid such issues to the future.
Thanks for your support.

**Comment by moarychan** [comment] 2020-09-01 08:00
Hi @kpapadopoul , thanks for your trying. We are retiring this starter, please check new repo [azure-spring-boot-sample-storage-blob](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-storage-blob), I check the default propertiy item `azure.storage.enable-https=true`, maybe need to emphasize this setting in readme. Now we will close this issue.

**Comment by chenrujun** [comment] 2021-03-09 08:18
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:18 UTC
Labels: azure-spring, storage
