### ISSUE TITLE
Azure Key vault secret names are lowercased, prevents configuring default datasource with the Grails framework

### ISSUE THREAD

**Issue by olavgg** [microsoft/azure-spring-boot#799] opened 2019-12-20 13:47 UTC
## Environment
- Grails 4.0.1 (Based on Spring Boot 2.1)

## Summary
This line https://github.com/microsoft/azure-spring-boot/blob/646a458325bd564fd0a1f33d617c4df55662d008/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L159 will lowercase the secret-name `dataSource-url` and map it to `datasource.url`

Grails however read the configuration property as `dataSource.url`
See https://github.com/grails/grails-data-mapping/blob/3e9ce320b1e5c89c2969973b78f1e3f6ffa62ffb/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/config/Settings.java#L66

Is there a reason secret names has to be lowercased?

**Comment by saragluna** [comment] 2019-12-24 09:50
Thanks for bringing this up. The reason why secret names are lowercased is that object name is case insensitive in Key Vault.

**Comment by V1ct0rV** [comment] 2020-05-11 22:22
Hi, 

I'm using an application that needs the properties in the correct Case, I'm adding to KeyVault with the proper case but Key Vault Operation is changing to lowercase....

Is there a way to avoid this and use original case?

Thanks in advance.

**Comment by saragluna** [comment] 2020-05-13 07:35
@V1ct0rV 

Could you please share your scenario, like when and where you need to leverage the property name with the correct case? 
And for your question, you could set another entry in the properties file, to reference the one configured in the key vault, like `propertyWithCorrectCase=${propertyConfiguredInKeyVault}`.

**Comment by V1ct0rV** [comment] 2020-05-13 19:20
Hi, I want to load application properties from Azure Key Vault through Config Server, so I create an Azure Key Vault Backend, it is working, but all the secret keys on Azure KeyVault are in lowercase and one of our config server client, specifically the one in dotnet-core is case sensitive, so is not loading those secrets..

**Comment by seanli1988** [comment] 2020-05-14 01:58
I'm raising a feature request to the Azure key vault team to support case sensitivity. You can help by cast your vote here. https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/33931111-secret-names-do-not-support-special-characters

**Comment by V1ct0rV** [comment] 2020-05-14 05:35
> I'm raising a feature request to the Azure key vault team to support case sensitivity. You can help by cast your vote here. https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/33931111-secret-names-do-not-support-special-characters

Case sensitivity is no related with key vault, Key vault send secrets with proper case, this line on `KeyVaultOperation.java` is the root cause:

https://github.com/microsoft/azure-spring-boot/blob/646a458325bd564fd0a1f33d617c4df55662d008/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L159

**Comment by saragluna** [comment] 2020-05-14 05:38
@V1ct0rV Yes, that's the root cause. We're trying to fix the issue now.

**Comment by chenrujun** [comment] 2021-03-09 08:50
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:50 UTC
Labels: azure-spring, key vault
