### ISSUE TITLE
Multi factor authenication requested

### ISSUE THREAD

**Issue by chufgard** [microsoft/azure-spring-boot#722] opened 2019-09-27 13:13 UTC
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 11 

## Summary
We want to use azure-active-directory-spring-boot-starter 2.1.7 to login users to our web application. While the login works for some users, other are caught in a redirection loop that is eventually stopped by the browser they use.

In the backend log I can see a list of exceptions like this:

> [Correlation ID: 59d22bd4-a14d-40cf-b112-0ee0aadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
 com.microsoft.aad.adal4j.AdalClaimsChallengeException: {"error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID: cfa3b062-230d-4b3a-83bb-b78899106a00\r\nCorrelation ID: 59d22bd4-a14d-40cf-b112-0ee0aadfeed5\r\nTimestamp: 2019-09-27 12:47:55Z","error":"interaction_required","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50076"} 

## Expected Results
The login should either work or display a screen to the user asking for MFA validation.

## Actual Results
Users cannot log in.

**Comment by neuqlz** [comment] 2019-10-08 13:09
Hi:
Thanks for your feedback, We will inspect it and give you a response later.

**Comment by chufgard** [comment] 2019-10-08 13:14
Another thing that might be relevant is, that we log in using federated accounts. When we login to the azure portal using the same accounts, we have to answer two MFA challenges - one for our company and a second for the tenant owner.

**Comment by neuqlz** [comment] 2019-11-13 03:33
Hi @chufgard,
sorry for the late response, now I am going to investigate your issue now. Could you provide more details? For example, your WebSecurityConfigurerAdapter config, your properties(except sensitive data). And if you can provide a sample project, that will be better.

**Comment by neuqlz** [comment] 2019-11-13 03:36
@chufgard  I have tried some samples, and I can't reproduce your issue.

**Comment by chufgard** [comment] 2019-11-13 06:59
> Hi @chufgard,
> sorry for the late response, now I am going to investigate your issue now. Could you provide more details? For example, your WebSecurityConfigurerAdapter config, your properties(except sensitive data). And if you can provide a sample project, that will be better.

Sample project will be difficult - at least since the whole stuff works like a charm if I deploy it on my local machine. Only running in azure it breaks.

We are assuming that the problem might be caused by a federated AD scenario plus a conditional access policy (access only from company IPs) bound to the ad where we are federated into.

**Comment by neuqlz** [comment] 2019-11-13 10:47
> > Hi @chufgard,
> > sorry for the late response, now I am going to investigate your issue now. Could you provide more details? For example, your WebSecurityConfigurerAdapter config, your properties(except sensitive data). And if you can provide a sample project, that will be better.
> 
> Sample project will be difficult - at least since the whole stuff works like a charm if I deploy it on my local machine. Only running in azure it breaks.
> 
> We are assuming that the problem might be caused by a federated AD scenario plus a conditional access policy (access only from company IPs) bound to the ad where we are federated into.

yep, I got your point. But there still need some investigate to prove it and find a solution. Could you provide a sample project, I will try it by running it in Azure. BTW: how do you run your application in Azure? By app service or VM?

**Comment by chufgard** [comment] 2019-11-13 11:19
The application is deployed in a kubernetes cluster.

**Comment by neuqlz** [comment] 2019-11-14 02:40
> The application is deployed in a kubernetes cluster.

okay, I got it. And I still need your properties and WebSecurityConfigurerAdapter or some minimal sample codes, not a sample project. So I can reproduce your issue, otherwise, it is difficult for me to reproduce it. Could you provide these to ours?

**Comment by neuqlz** [comment] 2019-12-03 02:51
hi @chufgard, I got a question, where did you get that error log? In your application backend log? Could you give more logs about the error? Because we don't use aad SDK in AzureActiveDirectorySpringBootStarter, so it's strange that you get that log in the backend.

**Comment by neuqlz** [comment] 2019-12-03 04:57
Hi @chufgard, could you provide more logs?

**Comment by neuqlz** [comment] 2020-01-15 06:39
Hi @chufgard,
I am working on this issue now, could you provide the conditional access policy you are using?

**Comment by neuqlz** [comment] 2020-01-20 09:23
Now this issue has been fixed in latest SNAPSHOT version.

**Closed by neuqlz** 2020-01-20 09:23 UTC
Labels: aad, bug

**Comment by zhoufenqin** [comment] 2020-08-03 09:35
https://github.com/microsoft/azure-spring-boot/pull/815/files
