### ISSUE TITLE
Access Token Response Unauthorized

### ISSUE THREAD

**Issue by hamdysdiri** [microsoft/azure-spring-boot#526] opened 2018-12-27 13:54 UTC
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows
- Java version: 
  - 1.8
  

## Summary

I followed the steps mentioned on the README.md file.
When I started my project, I had this error on the browser view:
`[invalid_token_response] An error occurred while attempting to recover the OAuth 2.0 access token. Answer: 401 not allowed`

Strangely, I run a project node.js using the same configuration on the file propreties and I managed to authenticate.

## Reproduce steps
Run the sample application and log in.

## Expected Results
Being able to log in and use the sample application

## Actual Results
Sample application did not respond to inputs.

**Comment by Incarnation-p-lee** [comment] 2018-12-28 00:55
@hamdysdiri 
Thanks for you issue. Could you please provide more information about the steps of reproducing ? Like your spring boot version, azure-spring-boot version, as well as how you configuration ?

**Comment by hamdysdiri** [comment] 2018-12-28 10:19
@Incarnation-p-lee I used spring boot starter 2.1.0. 
My azure spring boot version is 2.0.4

I follow the steps mentioned on here :https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?view=azure-java-stable

My goal is to authenticate with ad azure and got the id token using spring boot.

**Comment by Incarnation-p-lee** [comment] 2018-12-28 14:33
@hamdysdiri 
There is one restriction for integration with spring boot. Azure spring boot 2.0.x is for spring boot 2.0.x, and 
azure spring boot 2.1.x is for spring boot 2.1.x. Due to the gap between spring boot 2.0.x and 2.1.x, we need to align the version with spring boot.

So could you please have a try with azure spring boot 2.0.4 with spring boot 2.0.x ?

**Comment by fabadoo** [comment] 2019-01-02 19:19
Don't bother with dependenccy version, i've got the same problem ! (no solution)

In order to authenticate YOU HAVE TO "UrlEncode" the secret generated on portal.azure.com. 
It will escape caractères like "/" or "=" or "+" of the secret. 
from "...z/S+j+S2hYOZLc=" to "...z%2FS%2Bj%2BS2hYOZLc%3D"

The Base64 Basic Authorization header is correctly created, and you successfully obtain your JWT Bearer !
So far so good ! BUT... (at least for me)

Just after that, "AzureADGraphClient.acquireTokenForGraphApi()" method is called....  and the request fail caused by ? guess !! 
An invalid secret : " AuthenticationException: {"error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided "
...
I hope this will be clarified cause i feel deeply lost...

**Comment by Incarnation-p-lee** [comment] 2019-01-03 00:58
@fabadoo 
Thanks for you information and issue but looks your issue is quit different, could you please help to open another issue for this ? Thanks in advance!

**Comment by Incarnation-p-lee** [comment] 2019-01-04 00:57
@fabadoo 
Great! It is quite tricky here. Any other question/issue please feel free to contact us.

**Comment by fgoulet** [comment] 2019-01-31 20:02
Same problem here, even running the azure-active-directory-spring-boot-backend-sample.

In application.properties, I have a "/" in spring.security.oauth2.client.registration.azure.client-secret value. 

I tried encoding the value in utf-8 with urlencode.com but no luck, i got the error
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 718703cb-89ad-439c-9167-0f33907d3900\r\nCorrelation ID: 7c791472-4932-47a9-93af-16fcaadfeed5\r\nTimestamp: 2019-01-31 19:58:52Z","error":"invalid_client"}

Am I missing something ?

**Comment by tiltoam** [comment] 2019-02-01 13:23
I'm also having this issue. I have both a "+" and a "=" in my client-secret.

When I use azure spring boot 2.0.10 and spring boot 2.0.8, there's no problem. But when I switch to azure spring boot 2.1.0 and spring boot 2.1.0, I have the issue. The Base64 encoded authorization code fails the token request because the client-secret part of the authorization code includes characters that need to be url encoded but aren't. When I change my application.properties to an url encoded client-secret, the token request succeeds, but then the Azure Graph API request fails because the client-secret part of the authorization code _is_ url encoded.

Using Oauth2 in spring boot 2.0.8 pulls in spring security oauth2 client v5.0.11 which uses org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClient as a default. The NimbusAuthorizationCodeTokenResponseClient calls com.nimbusds.oauth2.sdk.auth.ClientSecretBasic.toHTTPAuthorizationHeader() to build the authorization header which _does_ url encode the client-secret.

But Oauth2 in spring boot 2.1.0 pulls in spring security oauth2 client v.5.1.1 which uses org.springframework.security.oauth2.client.endpoint.DefaultAuthorizationCodeTokenResponseClient as the default instead. The DefaultAuthorizationCodeTokenResponseClient calls org.springframework.HttpHeaders.setBasicAuth(String, String, Charset) to build the authorization header which _does not_ url encode the client-secret.

Could the actual issue be that the Azure token endpoint _requires_ the authorization be url encoded while the Azure Graph API endpoint requires that the authorization _not_ be url encoded?

**Comment by Incarnation-p-lee** [comment] 2019-02-02 01:04
@tiltoam
Thanks a lot for analysis the details of url encoding when secret contains `+` and `=`. There is one related issue about nimbus conflict from spring security to adaj here. https://github.com/spring-projects/spring-security/issues/6284.

For convention, we need to take care of url encoding out of hostname part, like headers, parameters. We may prepare the PR to encoding each part from user later. Could you please open another issue for this, so we can track the issue with PR easily.

**Comment by reshmasingh** [comment] 2019-03-22 22:41
Any update on this ticket? We really need to get this fixed as its breaking our application integration with Azure AD.

**Comment by Incarnation-p-lee** [comment] 2019-03-23 09:23
@reshmasingh 
If you mean the reserved char from url like this [issue](https://github.com/Microsoft/azure-spring-boot/issues/559), we have fix that with [newest](https://github.com/Microsoft/azure-spring-boot/releases/tag/2.1.6) version. You can have a try at first. 

If not url encoding related, please open new issue for tracking and details. Thanks a lot.

**Comment by afrancoc2000** [comment] 2019-04-22 15:44
Hi, 

I'm having the same problem but with a variation this are my dependencies:
    
    project.ext.springsecurity = [ 'com.microsoft.azure:azure-active-directory-spring-boot-starter:2.1.6',
          			       'org.springframework.boot:spring-boot-starter-security:2.1.4.RELEASE', 
				       'org.springframework.security:spring-security-core:5.1.5.RELEASE',
				       'org.springframework.security:spring-security-oauth2-client:5.1.5.RELEASE',
				       'org.springframework.security:spring-security-oauth2-jose:5.1.5.RELEASE',
				       'com.nimbusds:oauth2-oidc-sdk:5.64.4']
    project.ext.spring = [ 'org.springframework.boot:spring-boot-starter-web:2.1.4.RELEASE' ]

So both are 2.1.x

When I try this application.properties file:

    spring.security.oauth2.client.registration.azure.client-id=XXXXXXXXXX
    spring.security.oauth2.client.registration.azure.client-secret=XXXXXXXXXX
    azure.activedirectory.tenant-id=XXXXXXXXXXX
    azure.activedirectory.active-directory-groups=some-groups

Everything works well.

But my app is a multitenant app and I need to adjust the parameters I'm using so I changed my properties to this:

    spring.security.oauth2.client.registration.azure.client-id=XXXXXXXXXX
    spring.security.oauth2.client.registration.azure.client-secret=XXXXXXXXXX
    spring.security.oauth2.client.registration.azure.client-name=Azure
    spring.security.oauth2.client.registration.azure.provider=azure-oauth-provider
    spring.security.oauth2.client.registration.azure.scope=openid, https://graph.microsoft.com/user.read
    spring.security.oauth2.client.registration.azure.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
    spring.security.oauth2.client.registration.azure.client-authentication-method=basic
    spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code

    spring.security.oauth2.client.provider.azure-oauth-provider.authorization-uri=https://login.microsoftonline.com/{my-tenant-id}/oauth2/authorize
    spring.security.oauth2.client.provider.azure-oauth-provider.token-uri=https://login.microsoftonline.com/{my-tenant-id}/oauth2/token
    spring.security.oauth2.client.provider.azure-oauth-provider.user-info-uri=https://login.microsoftonline.com/{my-tenant-id}/openid/userinfo
    spring.security.oauth2.client.provider.azure-oauth-provider.jwk-set-uri=https://login.microsoftonline.com/{my-tenant-id}/discovery/keys
    spring.security.oauth2.client.provider.azure-oauth-provider.user-name-attribute=name

    azure.activedirectory.tenant-id=XXXXXXXXXXX
    azure.activedirectory.active-directory-groups=some-groups

And changed oauth2AllowImplicitFlow in your application manifest to true, and then I get the 401 [invalid_token_response] error. If I encode the secret I get an error saying the secret is wrong so, thats not it, I've tried changing this properties a little but nothing works.

Any ideas?

Thanks

**Comment by Incarnation-p-lee** [comment] 2019-04-23 00:19
Thanks for issue this, could you please use following
`spring.security.oauth2.client.registration.azure.client-authentication-method=post` and `azure.activedirectory.tenant-id=common` instead of basic and have a try again ?
If not works, that should be another issue here.

**Comment by afrancoc2000** [comment] 2019-04-23 01:07
Thanks! it works! 😄

**Comment by 001arthur** [comment] 2019-07-12 19:59
@Incarnation-p-lee I'm facing the same problem, I have already tried your solution but the problem persists, any ideia?

**Comment by Incarnation-p-lee** [comment] 2019-07-15 00:52
@001arthur 
You may need to provide more information, like spring boot version, sdk version and minimal code for reproducing.

**Comment by 001arthur** [comment] 2019-07-15 13:34
@Incarnation-p-lee The spring boot version is 2.1.6.RELEASE. 
The code is very similar with the another one.

	spring.security.oauth2.client.registration.azure.client-id=XXXXXXXXXX
	spring.security.oauth2.client.registration.azure.client-secret=XXXXXXXXXX
	spring.security.oauth2.client.registration.azure.client-name=Azure
	spring.security.oauth2.client.registration.azure.provider=azure-oauth-provider
	spring.security.oauth2.client.registration.azure.scope=openid, https://graph.microsoft.com/user.read
	spring.security.oauth2.client.registration.azure.redirect-uri-template=http://localhost:8080/login/oauth2/code/
	spring.security.oauth2.client.registration.azure.client-authentication-method=post
	spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code

	spring.security.oauth2.client.provider.azure-oauth-provider.authorization-uri=https://login.microsoftonline.com/organizations/oauth2/authorize
	spring.security.oauth2.client.provider.azure-oauth-provider.token-uri=https://login.microsoftonline.com/organizations/oauth2/token
	spring.security.oauth2.client.provider.azure-oauth-provider.user-info-uri=https://login.microsoftonline.com/organizations/openid/userinfo
	spring.security.oauth2.client.provider.azure-oauth-provider.jwk-set-uri=https://login.microsoftonline.com/organizations/discovery/keys
	spring.security.oauth2.client.provider.azure-oauth-provider.user-name-attribute=name

	azure.activedirectory.tenant-id=organizations
	azure.activedirectory.active-directory-groups=some-groups

And the configuration is:

	@EnableWebSecurity
	@EnableGlobalMethodSecurity(prePostEnabled = true)
	public class WebSecurityConfig extends WebSecurityConfigurerAdapter{

	@Autowired
	private OAuth2UserService<OidcUserRequest, OidcUser> oidcUserService;
	
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
			.anyRequest().authenticated()
			.and()
			.oauth2Login()
			.userInfoEndpoint()
			.oidcUserService(oidcUserService);
	}

**Comment by Incarnation-p-lee** [comment] 2019-07-15 23:56
Just confirm, it is something similar to aad backend sample ?

**Comment by ppartarr** [comment] 2020-03-24 15:23
HI @Incarnation-p-lee I'm having the same problem the azure. I put a lengthy description of the version on [stackoverflow](https://stackoverflow.com/questions/60303916/why-am-i-getting-an-invalid-token-response-when-exchanging-an-authorization-code).

I've tried all the solutions mentioned above without any success.

**Comment by saragluna** [comment] 2020-03-25 13:07
@ppartarr 
Have you tried with setting `spring.security.oauth2.client.registration.azure.client-authentication-method=post`?

**Comment by DineshNO** [comment] 2020-04-04 09:23
> Thanks for issue this, could you please use following
> `spring.security.oauth2.client.registration.azure.client-authentication-method=post` and `azure.activedirectory.tenant-id=common` instead of basic and have a try again ?
> If not works, that should be another issue here.

Hi,
I am facing the same issue when using okta.
[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]

id("org.springframework.boot") version "2.2.4.RELEASE"

**Comment by millionseleshi** [comment] 2020-05-04 16:32
migrated to this 

**id 'org.springframework.boot' version `'2.2.6.RELEASE' 
azure-active-directory-spring-boot-starter:2.2.0**

application.yml

```
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <client-id>
            client-secret: <client-secret>
azure:
  activedirectory:
    tenant-id: <tenent-id>
    app-id-uri: <app-id-url>
    user-group:
      allowed-groups: Users
```

**Note**:-  azure.activedirectory.active-directory-groups=group1, group2.... this is deprecated

**Comment by saragluna** [comment] 2020-06-09 06:01
Closing this issue.

**Closed by saragluna** 2020-06-09 06:01 UTC
Labels: aad

**Comment by ShaguftaSyed** [comment] 2021-05-31 19:40
I'm facing same issue. The details are [here](https://stackoverflow.com/questions/67779378/azure-ad-oauth-integration-in-sprint-boot-gives-401-unauthorized). Changing spring.security.oauth2.client.registration.azure.client-authentication-method=post does not help.

**Comment by chenrujun** [comment] 2021-06-01 01:41
@ShaguftaSyed, could you please try our latest version of [azure-spring-boot-starter-active-directory](https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-starter-active-directory)? Which work for spring-boot 2.4.5.

**Comment by ShaguftaSyed** [comment] 2021-06-01 06:43
@chenrujun, Thank you for your response but using above sample, after the authorization code is received it is taking me to page login?error that says invalid credentials.
![OAuthCapture](https://user-images.githubusercontent.com/80444066/120278305-c04b1980-c2d2-11eb-98a1-deb6d47766d0.PNG)

**Comment by ShaguftaSyed** [comment] 2021-06-01 08:53
@chenrujun, Thank for looking into my issue. It wasn't related to code but had to enable sticky session on ECS service's Application Load Balancer.

**Comment by chenrujun** [comment] 2021-06-02 00:29
Hi, @ShaguftaSyed, could you please use this sample instead?

https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp

**Comment by guidobonerz** [comment] 2024-04-20 15:40
Has anybody a hint why oauth2 authentication for my springboot 3 app only works properly from my local machine localhost but not after I deloyed it to web app service in azure?
I get the following error
[invalid_token_request] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]

Best regards
G

**Comment by NTejaswi1** [comment] 2024-06-25 14:09
> Has anybody a hint why oauth2 authentication for my springboot 3 app only works properly from my local machine localhost but not after I deloyed it to web app service in azure? I get the following error [invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]
> 
> Best regards G

Same problem here, Did you figured it out?
