### ISSUE TITLE
@ConfigurationProperties not mapping correctly

### ISSUE THREAD

**Issue by jokarl** [microsoft/azure-spring-boot#641] opened 2019-03-26 15:13 UTC
## Environment
- Spring boot starter: key vault spring boot starter 2.1.6
- OS Type: Linux
- Java version: 11.0.1
  

## Summary
I would like to get properties from the vault from classes annotated with `@ConfigurationProperties`, but this is not possible.

It seems like it should be possible, right now the starter keeps two versions of the property added if it contains a dash:

`prefix-clientsecret` and `prefix.clientsecret`. 

The latter of these contains a valid prefix for use with the `@ConfigurationProperties` annotation:

> A valid prefix is defined by one or more words separated with dots

## Reproduce steps

1. Add a secret (`prefix-clientSecret`) to the vault
2. Create a configuration class:

```java
@Getter
@Configuration
@ConfigurationProperties(prefix = "prefix")
public class SampleConfiguration {
	private String clientSecret;
}
```

When binding the above bean, clientSecret will be null.

## Expected Results
The value of the key in the vault is reflected in the property in the application.

## Actual Results
Bound property is null.

**Comment by Incarnation-p-lee** [comment] 2019-03-27 05:12
@hochas
Thanks for issue this, current this feature is not supported. But for `prefix`, I am not sure only `prefix` is compatible with `EnumerablePropertySource`.

Because `EnumerablePropertySource` `getProperty` method only take care of `prefix`, for example as you above code `prefix-clientSecret`, when `getProperty` with `prefix`, only the `prefix` will be available. Which means we need to add all properties with `prefix` from source. 

It will need further investigation anyway.

**Comment by hochas** [comment] 2019-03-27 15:23
I created a completely clean project with only the key vault dependency and it works, the issue is with my setup. I'm using a multi module maven project so that might be an issue.

**Comment by Incarnation-p-lee** [comment] 2019-03-28 00:47
@hochas 
Could you please share your sample code ? I think multi-module should be the same scenario.

**Comment by hochas** [comment] 2019-03-28 07:54
I'm sorry, I think the issue is with my code. I've tried to create a sample that recreates the behavior but it works in every scenario I've tried. So very likely my setup is just broken somehow, just haven't figured out how yet.

**Comment by hochas** [comment] 2019-03-28 10:32
I'm sorry for all this back and forth, but I managed to replicate it in an [isolated project](https://github.com/hochas/keyvault-config-issue).

To launch, supply the following environment variables pointing to a vault:
- `keyVaultPrincipal`
- `keyVaultSecret`
- `keyVaultUri`

Add secrets matching the application, or modify the application to match your secrets.
The keyvault I'm working against looks like this, the sample is also set up to consume these properties:

![image](https://user-images.githubusercontent.com/6864214/55149284-2dd6ea80-514a-11e9-8aba-449f71c1d8b1.png)

In `Application.java`, I haved injected a number of classes that fetch properties.

- **DataLakeConfiguration** uses `@ConfigurationProperties(prefix = "gate")`, it should get properties form the keyvault and _does not work_.
- **ProvisioningConfiguration** uses the `@Value` annotation and can correctly fetch properties
- **ProvisioningConfigurationWithConfigurationProperties** uses `@ConfigurationProperties(prefix = "gate")`, it should get properties form the keyvault and _does not work_.
- **SpringProperties** fetches one property declared in `src/main/resources/application.properties`. it uses `@ConfigurationProperties(prefix = "spring.application")` and _works_.

As a tool I am also outputting:
- The _type_ of the property sources
- Each property name and its value that belongs to each property source

The property from `SpringProperties` comes from a property source of type `OriginTrackedMapPropertySource`. When I run this I also see  that calling `getPropertyNames` of `KeyVaultPropertySource` does not return properties separated by `.`, which might be an issue. However, calling `get` on `KeyVaultOperation` will match, for instance, `prefix.property` to `prefix-property` thanks to the method `getKeyvaultSecretName`.

I am not entirely sure about this conclusion, but I think the method [`list`](https://github.com/Microsoft/azure-spring-boot/blob/2.1.6/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L46) should not only return the keyvault representation of a property, but also separated by `.` as well.

**Comment by hochas** [comment] 2019-03-28 11:45
I rewrote the method [`list`](https://github.com/Microsoft/azure-spring-boot/blob/2.1.6/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L46) and tested my application with `2.1.7-SNAPSHOT` with my modified method and it resolves my problem, but I don't know if this is the root cause.
```java
public String[] list() {
    try {
        this.rwLock.readLock().lock();
        final KeySetView<String, Object> keys = propertyNamesHashMap.keySet();
        return Stream.concat(keys.stream(),
                keys.stream().map(k -> k.replace("-", "."))).toArray(String[]::new);
    } finally {
        this.rwLock.readLock().unlock();
    }
}
```

**Comment by Incarnation-p-lee** [comment] 2019-03-28 14:37
@hochas 
Thanks for figuring out this. It looks that the processor will eliminate the works after `-`. I did some validation for this, for example:

Assume you got keyvault secrets `test-value` from azure. When `list`, it will return the list contains `test-value`. But later when `get` the char after `-` (here means `-value`) is cut by framework and only `test` is here.

So from list, I think you code should fix the problem. Could you prepare one PR for this ?

**Comment by hochas** [comment] 2019-03-28 15:12
No problem, glad to help!

I'm not sure why this specific setup seems to break it though, when I created a minimal setup with only the keyvault starter it seemed to work. I will create another sample with that scenario next week, if you still determine that the fault lies with the starter I will gladly create a PR. In the mean time, hope you have a nice weekend!

**Comment by hochas** [comment] 2019-04-01 13:31
@Incarnation-p-lee I have confirmed  that [`2.1.6`](https://github.com/Microsoft/azure-spring-boot/blob/2.1.6/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L84) is broken, [`2.1.2`](https://github.com/Microsoft/azure-spring-boot/blob/2.1.2/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L56) works. [Check out this line](https://github.com/Microsoft/azure-spring-boot/blob/2.1.2/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L94), you populate your internal property map with _both_ the `.` _and_ `-` separated properties. I think this is more efficient than my above suggestion since this way it is only done once, my solution runs on every property lookup.

**Comment by Incarnation-p-lee** [comment] 2019-04-01 13:41
@hochas 
Make sense. For support relaxing names as, removing that in previous. We need to double check how normal `@ConfigurationProperties` works, and then can add replacing properties back here with the real reason.

Thanks for issue this.
```
     * <tr><td>Spring relaxed binding names</td></tr>
     * <tr><td>acme.my-project.person.first-name</td></tr>
     * <tr><td>acme.myProject.person.firstName</td></tr>
     * <tr><td>acme.my_project.person.first_name</td></tr>
     * <tr><td>ACME_MYPROJECT_PERSON_FIRSTNAME</td></tr>
```

**Comment by hochas** [comment] 2019-04-01 14:15
Given this class:

```java
@Configuration
@ConfigurationProperties(prefix = "prefix")
public class Config {

	@Getter
	@Setter
	private String sampleProperty;
}
```

The `get` method in `KeyVaultOperation` will be called with `prefix.sample-property`. From your perspective, I'm not sure if you need to consider all the above permutations. The use cases with the vault starter are:

1. `@Value("prefix.sampleProperty")`
2. `@Value("prefix-sampleProperty")`
3. The above class which results in `prefix.sample-property` being looked up

Spring supports all the permutations above because properties might be coming from many different sources; `.yml`, `.properties` or environment variables. In your case you know that your properties can have only one separator, and that is `-`. I think you only need to consider your single source. I might be wrong though, I've been looking at this for too long now.

**Comment by Incarnation-p-lee** [comment] 2019-04-01 15:07
Thanks for the sample, I take a look into normal `@ConfigurationProperties` code, it works like this,

```java
@ConfigurationProperties(prefix = "test")
public class Test {

	@Getter
	@Setter
	private String value;
}
```
* First the instance will be created by default constructor.
* Then ConfigurationPropertiesBinder will find property by `prefix`, here is test.
* In fact, no properties named `test`
* And next, it notices Test is class, it will iterator all fields under class Test.
* For each field, it will append field name to prefix, here it will get `test.value`
* And then find `test.value` for all properties source.

The most code locate at `javaBeanBinder`.

Back to this case, as keyvault do not support `.` in secret name, and only '-' is available, we have no choose to leverage `-` as prefix separator if we want to support `ConfigurationProperties`. Which means both `test-value` and `test.value` will existed.

There is another issue about this, assume I have `test-value` in keyvault. I want to leverage `test-value` from keyvault to my application. And then I add new property to may `application.yml`, named `test.value`. And then the `test.value` from keyvault may override the one from `application.yml`.

Anyway, I will file one PR for this and make `@ConfigurationPropeties` work at first.

**Comment by hochas** [comment] 2019-04-02 05:42
I think overriding will always be an issue either way. If you document where in [this hierarchy](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config) that the key vault is applied, I think it is fine. Thanks for your time, I'll be on the lookout for a new release :)

**Comment by Incarnation-p-lee** [comment] 2019-04-02 06:04
OK. You can leverage our SNAPSHOT version at first.

**Comment by chenrujun** [comment] 2021-03-09 08:18
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 08:18 UTC
Labels: azure-spring, key vault
