### ISSUE TITLE
Error - The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by ankurjasoria** [Microsoft/azure-spring-boot#250] opened 2018-01-24 09:13 UTC
Hi All I am facing issue "The specified CGI application encountered an error and the server terminated the process." after hosting it on Azure Web Sites. On Local it works fine. I have developed application on asp.net core 1.0 and deployed on Azure.

Is there any timeout issue or any thing missing when deployed code on azure ?
Please help me out regarding this issue.

**Comment by yungez** [comment] 2018-01-26 01:42
@ankurjasoria  thanks for reporting the issue, could you share more detail of the issue? which starter you're using, and what's the deployment story? You mentioned it's asp.net application... little confusing..

**Comment by ankurjasoria** [comment] 2018-01-26 09:53
@yungez  Thanks for update !!!
I am unable to understand about "starter" ? Please share me some reference about same and apart that 
I am sharing you some details about my application as below

**Technology :** Asp.Net Core 1.0 DNX

**Project.Json :**
{
  "userSecretsId": "aspnet5-CenterManagementSystem.UI-44fef558-da8c-4457-b983-dfb0e1908e5b",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "AutoMapper": "5.0.2",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Glimpse": "2.0.0-beta1",
    "Glimpse.Agent.AspNet": "2.0.0-beta1",
    "Glimpse.Agent.AspNet.Mvc": "2.0.0-beta1",
    "Glimpse.Server": "2.0.0-beta1",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Moq": "4.5.29",
    "Newtonsoft.Json": "9.0.1",
    "System.IdentityModel.Tokens": "5.0.0-rc1-211161024"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "CenterManagementSystem.Platform": "1.0.0-*"
      }
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "gulp clean", "gulp min" ]
  }
}

**Web.Config :**
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>

Please check and update regarding issue.

**Comment by ankurjasoria** [comment] 2018-01-26 09:55
**Web.Config :**

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>

**Comment by yungez** [comment] 2018-02-27 09:11
@ankurjasoria  sorry for late response. Are you using java language? seems the issue is submitted in wrong place. This repo provdes Spring boot starters which is java framework. Not related with .net or ASP.

**Comment by xscript** [comment] 2018-11-21 02:19
@ankurjasoria We will close this issue because it is not related to our repo. In this repo, we host code for Spring Boot support on Azure. Spring Boot is a framework for Java language.
You can find more reference at [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet) and post your comment.

**Closed by xscript** 2018-11-21 02:19 UTC

**Comment by vaidehip-optimus** [comment] 2021-01-21 15:17
I am facing this issue "the specified cgi application encountered an error and the server terminated the process" on deploying jar file.

**Comment by shaimagawankar** [comment] 2021-11-24 16:35
hi i am facing this issue while deploying spring boot war file to azure app service . Can anyone guide

**Comment by shaimagawankar** [comment] 2021-11-24 16:36
"The specified CGI application encountered an error and the server terminated the process."

My WebConfig :

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%JAVA_HOME%\bin\java.exe"
        arguments="-Djava.net.preferIPv4Stack=true -Dserver.port=%HTTP_PLATFORM_PORT% -jar &quot;%HOME%\site\wwwroot\app.war&quot;">
    </httpPlatform>
  </system.webServer>
</configuration>
